//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.UserLogins = new HashSet<UserLogin>();
            this.RoleStatusMappings = new HashSet<RoleStatusMapping>();
        }
    
        public int Role_Code { get; set; }
        public string Role_Name { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> User_Code { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string User_IP { get; set; }
        public Nullable<int> Company_Code { get; set; }
        public Nullable<int> TAT { get; set; }
        public Nullable<int> ApplicationId { get; set; }
    
        public virtual Setup_Application Setup_Application { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        public virtual ICollection<RoleStatusMapping> RoleStatusMappings { get; set; }
    }
}
