//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleStatusMapping
    {
        public int Status_Mapping_Id { get; set; }
        public int Role_Code { get; set; }
        public int StatusId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIp { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual TS_Setup_TicketStatus TS_Setup_TicketStatus { get; set; }
    }
}
