//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Employee
    {
        public Setup_Employee()
        {
            this.UserLogins = new HashSet<UserLogin>();
        }
    
        public int Emp_Id { get; set; }
        public string EmployeeName { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Setup_Department Setup_Department { get; set; }
        public virtual Setup_Designation Setup_Designation { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
    }
}
