//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_RequestTypeSubcategoryFieldValue
    {
        public int RequestTypeSubcategoryFieldValueId { get; set; }
        public Nullable<int> TicketMasterId { get; set; }
        public int RequestTypeSubcategoryFieldTypeId { get; set; }
        public string FieldValue { get; set; }
        public Nullable<int> RequestTypeSubcategoryFieldTypeDetailId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedDateInt { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedDateInt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    }
}
