//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Department
    {
        public Setup_Department()
        {
            this.Setup_Employee = new HashSet<Setup_Employee>();
            this.TS_TaskMaster = new HashSet<TS_TaskMaster>();
            this.TS_TicketDetail = new HashSet<TS_TicketDetail>();
            this.TS_TicketMaster = new HashSet<TS_TicketMaster>();
        }
    
        public int DepartmentId { get; set; }
        public string DepartmentPrefix { get; set; }
        public string DepartmentName { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsTeamAllowed { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
    
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
        public virtual ICollection<TS_TaskMaster> TS_TaskMaster { get; set; }
        public virtual ICollection<TS_TicketDetail> TS_TicketDetail { get; set; }
        public virtual ICollection<TS_TicketMaster> TS_TicketMaster { get; set; }
    }
}
