//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_ChatLog
    {
        public TS_ChatLog()
        {
            this.TS_ChatLogReadDetail = new HashSet<TS_ChatLogReadDetail>();
        }
    
        public int ChatLogId { get; set; }
        public int ChatTypeId { get; set; }
        public Nullable<int> TicketMasterId { get; set; }
        public Nullable<int> TaskMasterId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> AssigneeId { get; set; }
        public string Description { get; set; }
        public string Description_html { get; set; }
        public string EmailId { get; set; }
        public bool IsReply { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string FilePath { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedDateInt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedDateInt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TS_Setup_ChatType TS_Setup_ChatType { get; set; }
        public virtual TS_TaskMaster TS_TaskMaster { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual UserLogin UserLogin2 { get; set; }
        public virtual ICollection<TS_ChatLogReadDetail> TS_ChatLogReadDetail { get; set; }
    }
}
