//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Setup_City
    {
        public TS_Setup_City()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Sort { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
