//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Setup_TicketStatus
    {
        public TS_Setup_TicketStatus()
        {
            this.TS_StatusDetail = new HashSet<TS_StatusDetail>();
            this.TS_TaskDetail = new HashSet<TS_TaskDetail>();
            this.TS_TaskLog = new HashSet<TS_TaskLog>();
            this.TS_TaskMaster = new HashSet<TS_TaskMaster>();
            this.RoleStatusMappings = new HashSet<RoleStatusMapping>();
            this.TS_TicketDetail = new HashSet<TS_TicketDetail>();
            this.TS_TicketMaster = new HashSet<TS_TicketMaster>();
        }
    
        public int StatusId { get; set; }
        public string Status { get; set; }
        public bool IsInitiator { get; set; }
        public string imageUrl { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string BackgroundColor { get; set; }
    
        public virtual ICollection<TS_StatusDetail> TS_StatusDetail { get; set; }
        public virtual ICollection<TS_TaskDetail> TS_TaskDetail { get; set; }
        public virtual ICollection<TS_TaskLog> TS_TaskLog { get; set; }
        public virtual ICollection<TS_TaskMaster> TS_TaskMaster { get; set; }
        public virtual ICollection<RoleStatusMapping> RoleStatusMappings { get; set; }
        public virtual ICollection<TS_TicketDetail> TS_TicketDetail { get; set; }
        public virtual ICollection<TS_TicketMaster> TS_TicketMaster { get; set; }
    }
}
