//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Setup_TypeOfIssue
    {
        public TS_Setup_TypeOfIssue()
        {
            this.TS_Setup_ProductSubCategory = new HashSet<TS_Setup_ProductSubCategory>();
        }
    
        public int TypeOfIssueId { get; set; }
        public string TypeOfIssue { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<TS_Setup_ProductSubCategory> TS_Setup_ProductSubCategory { get; set; }
    }
}
