//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Setup_Priority
    {
        public TS_Setup_Priority()
        {
            this.TS_TaskMaster = new HashSet<TS_TaskMaster>();
            this.TS_TicketMaster = new HashSet<TS_TicketMaster>();
        }
    
        public int PriorityId { get; set; }
        public string PriorityName { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<TS_TaskMaster> TS_TaskMaster { get; set; }
        public virtual ICollection<TS_TicketMaster> TS_TicketMaster { get; set; }
    }
}
