//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_TaskDetail
    {
        public TS_TaskDetail()
        {
            this.TS_TaskLog = new HashSet<TS_TaskLog>();
        }
    
        public int TaskDetailId { get; set; }
        public int TaskMasterId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> AssigneeTo { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TS_Setup_TicketStatus TS_Setup_TicketStatus { get; set; }
        public virtual TS_TaskMaster TS_TaskMaster { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual ICollection<TS_TaskLog> TS_TaskLog { get; set; }
    }
}
