//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_TicketMaster
    {
        public TS_TicketMaster()
        {
            this.TS_TaskMaster = new HashSet<TS_TaskMaster>();
            this.TS_TicketDetail = new HashSet<TS_TicketDetail>();
            this.TS_TicketMeeting = new HashSet<TS_TicketMeeting>();
        }
    
        public int TicketMasterId { get; set; }
        public string TicketCode { get; set; }
        public Nullable<int> ParentTicketMasterId { get; set; }
        public Nullable<int> InitiatorId { get; set; }
        public Nullable<int> AssigneeId { get; set; }
        public int DepartmentId { get; set; }
        public int PriorityId { get; set; }
        public int StatusId { get; set; }
        public int RequestModeId { get; set; }
        public int RequestTypeId { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public string Tittle { get; set; }
        public string Description { get; set; }
        public string Description_html { get; set; }
        public System.DateTime TicketCreationDate { get; set; }
        public int TicketCreationDateInt { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedDateInt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.TimeSpan TicketCreationTime { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedDateInt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> LevelId { get; set; }
        public int TicketTypeId { get; set; }
        public Nullable<bool> IsFlagMark { get; set; }
        public Nullable<int> RequestTypeCategoryId { get; set; }
        public Nullable<int> RequestTypeSubCategoryId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> TypeOfIssueId { get; set; }
        public Nullable<int> TypeOfComplaintId { get; set; }
        public Nullable<int> ProductSubCategoryId { get; set; }
        public Nullable<int> Ticket_Reopen_DateInt { get; set; }
        public Nullable<System.DateTime> Ticket_Reopen_Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Setup_Department Setup_Department { get; set; }
        public virtual TS_Setup_Priority TS_Setup_Priority { get; set; }
        public virtual TS_Setup_RequestMode TS_Setup_RequestMode { get; set; }
        public virtual TS_Setup_RequestType TS_Setup_RequestType { get; set; }
        public virtual TS_Setup_RequestTypeCategory TS_Setup_RequestTypeCategory { get; set; }
        public virtual TS_Setup_RequestTypeSubcategory TS_Setup_RequestTypeSubcategory { get; set; }
        public virtual TS_Setup_TicketLevel TS_Setup_TicketLevel { get; set; }
        public virtual TS_Setup_TicketStatus TS_Setup_TicketStatus { get; set; }
        public virtual TS_Setup_TicketType TS_Setup_TicketType { get; set; }
        public virtual ICollection<TS_TaskMaster> TS_TaskMaster { get; set; }
        public virtual ICollection<TS_TicketDetail> TS_TicketDetail { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual ICollection<TS_TicketMeeting> TS_TicketMeeting { get; set; }
    }
}
