//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_TicketMeeting
    {
        public TS_TicketMeeting()
        {
            this.TS_TicketMeetingDetail = new HashSet<TS_TicketMeetingDetail>();
        }
    
        public int TicketMeetingId { get; set; }
        public Nullable<int> TicketMasterId { get; set; }
        public Nullable<System.TimeSpan> MeetingStartTime { get; set; }
        public Nullable<System.TimeSpan> MeetingEndTime { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public string MeetingAgenda { get; set; }
        public string MeetingDetail { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public bool IsActive { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedDateInt { get; set; }
    
        public virtual ICollection<TS_TicketMeetingDetail> TS_TicketMeetingDetail { get; set; }
        public virtual TS_TicketMaster TS_TicketMaster { get; set; }
    }
}
