//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_TicketMeetingDetail
    {
        public int TicketMeetingDetail { get; set; }
        public int TicketMeetingId { get; set; }
        public int AttendeeId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual TS_TicketMeeting TS_TicketMeeting { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
