//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_TaskMaster
    {
        public TS_TaskMaster()
        {
            this.TS_ChatLog = new HashSet<TS_ChatLog>();
            this.TS_TaskDetail = new HashSet<TS_TaskDetail>();
            this.TS_TaskLog = new HashSet<TS_TaskLog>();
            this.TS_TaskLog1 = new HashSet<TS_TaskLog>();
        }
    
        public int TaskMasterId { get; set; }
        public Nullable<int> TicketMasterId { get; set; }
        public string TaskTitle { get; set; }
        public Nullable<int> InitiatorId { get; set; }
        public Nullable<int> AssigneeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual Setup_Department Setup_Department { get; set; }
        public virtual ICollection<TS_ChatLog> TS_ChatLog { get; set; }
        public virtual TS_Setup_Priority TS_Setup_Priority { get; set; }
        public virtual TS_Setup_TicketStatus TS_Setup_TicketStatus { get; set; }
        public virtual ICollection<TS_TaskDetail> TS_TaskDetail { get; set; }
        public virtual ICollection<TS_TaskLog> TS_TaskLog { get; set; }
        public virtual ICollection<TS_TaskLog> TS_TaskLog1 { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        public virtual TS_TicketMaster TS_TicketMaster { get; set; }
    }
}
