//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_TicketDetail
    {
        public int TicketDetailId { get; set; }
        public int TicketMasterId { get; set; }
        public Nullable<int> AssigneeId { get; set; }
        public int StatusId { get; set; }
        public int DepartmentId { get; set; }
        public string Description { get; set; }
        public string Description_html { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UserIP { get; set; }
        public bool IsActive { get; set; }
        public int CreatedDateInt { get; set; }
        public Nullable<int> ModifiedDateInt { get; set; }
        public string EmailFrom { get; set; }
        public Nullable<int> FaultId { get; set; }
        public Nullable<int> CorrectiveActionId { get; set; }
        public Nullable<int> TypeOfIssueId { get; set; }
        public Nullable<int> TypeOfComplaintId { get; set; }
        public Nullable<int> ProductSubCategoryId { get; set; }
    
        public virtual Setup_Department Setup_Department { get; set; }
        public virtual TS_Setup_TicketStatus TS_Setup_TicketStatus { get; set; }
        public virtual TS_TicketMaster TS_TicketMaster { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
