//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_TicketAttachments
    {
        public int FileId { get; set; }
        public Nullable<int> TargetId { get; set; }
        public string Filename { get; set; }
        public string Filecomments { get; set; }
        public string Filetype { get; set; }
        public string FileOriginalName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
