//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public UserLogin()
        {
            this.Setup_Employee = new HashSet<Setup_Employee>();
            this.Setup_Employee1 = new HashSet<Setup_Employee>();
            this.TS_ChatLog = new HashSet<TS_ChatLog>();
            this.TS_ChatLog1 = new HashSet<TS_ChatLog>();
            this.TS_ChatLog2 = new HashSet<TS_ChatLog>();
            this.TS_TaskDetail = new HashSet<TS_TaskDetail>();
            this.TS_TaskDetail1 = new HashSet<TS_TaskDetail>();
            this.TS_TaskLog = new HashSet<TS_TaskLog>();
            this.TS_TaskMaster = new HashSet<TS_TaskMaster>();
            this.TS_TaskMaster1 = new HashSet<TS_TaskMaster>();
            this.TS_TicketCC = new HashSet<TS_TicketCC>();
            this.TS_TicketComment = new HashSet<TS_TicketComment>();
            this.TS_TicketComment1 = new HashSet<TS_TicketComment>();
            this.TS_TicketMeetingDetail = new HashSet<TS_TicketMeetingDetail>();
            this.UserLoginHistories = new HashSet<UserLoginHistory>();
            this.TS_ChatLogReadDetail = new HashSet<TS_ChatLogReadDetail>();
            this.TS_TicketDetail = new HashSet<TS_TicketDetail>();
            this.TS_TicketMaster = new HashSet<TS_TicketMaster>();
            this.TS_TicketMaster1 = new HashSet<TS_TicketMaster>();
        }
    
        public int User_Code { get; set; }
        public Nullable<int> Emp_Id { get; set; }
        public string Full_Name { get; set; }
        public string Login_ID { get; set; }
        public string Password { get; set; }
        public int Role_Code { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime Created_Date { get; set; }
        public bool Is_Active { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string User_IP { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
        public virtual ICollection<Setup_Employee> Setup_Employee1 { get; set; }
        public virtual Setup_Employee Setup_Employee2 { get; set; }
        public virtual ICollection<TS_ChatLog> TS_ChatLog { get; set; }
        public virtual ICollection<TS_ChatLog> TS_ChatLog1 { get; set; }
        public virtual ICollection<TS_ChatLog> TS_ChatLog2 { get; set; }
        public virtual ICollection<TS_TaskDetail> TS_TaskDetail { get; set; }
        public virtual ICollection<TS_TaskDetail> TS_TaskDetail1 { get; set; }
        public virtual ICollection<TS_TaskLog> TS_TaskLog { get; set; }
        public virtual ICollection<TS_TaskMaster> TS_TaskMaster { get; set; }
        public virtual ICollection<TS_TaskMaster> TS_TaskMaster1 { get; set; }
        public virtual ICollection<TS_TicketCC> TS_TicketCC { get; set; }
        public virtual ICollection<TS_TicketComment> TS_TicketComment { get; set; }
        public virtual ICollection<TS_TicketComment> TS_TicketComment1 { get; set; }
        public virtual ICollection<TS_TicketMeetingDetail> TS_TicketMeetingDetail { get; set; }
        public virtual ICollection<UserLoginHistory> UserLoginHistories { get; set; }
        public virtual ICollection<TS_ChatLogReadDetail> TS_ChatLogReadDetail { get; set; }
        public virtual ICollection<TS_TicketDetail> TS_TicketDetail { get; set; }
        public virtual ICollection<TS_TicketMaster> TS_TicketMaster { get; set; }
        public virtual ICollection<TS_TicketMaster> TS_TicketMaster1 { get; set; }
    }
}
